### ISSUE TITLE
Getting a traceback when trying to bootstrap 

### ISSUE THREAD

**Issue by i5uhail** [johanlundberg/neo4j-django-tutorial#11]
I have followed the tutorial and on doing the bootstrap I am getting the below traceback. 

Am i Doing something wrong or its an issue. 

(tutorialenv) m-mymachine:neo4j-django-tutorial suhail$ python neo4jtut/manage.py bootstrap
Traceback (most recent call last):
  File "neo4jtut/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/suhail/Workspace/neo4j/neo4j-django-tutorial/tutorialenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/suhail/Workspace/neo4j/neo4j-django-tutorial/tutorialenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/suhail/Workspace/neo4j/neo4j-django-tutorial/tutorialenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/suhail/Workspace/neo4j/neo4j-django-tutorial/tutorialenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/Users/suhail/Workspace/neo4j/neo4j-django-tutorial/tutorialenv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/suhail/Workspace/neo4j/neo4j-django-tutorial/neo4jtut/neo4japp/management/commands/bootstrap.py", line 70, in <module>
    Command().handle()
  File "/Users/suhail/Workspace/neo4j/neo4j-django-tutorial/neo4jtut/neo4japp/management/commands/bootstrap.py", line 50, in handle
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/Users/suhail/Workspace/neo4j/neo4j-django-tutorial/neo4jtut/neo4jtut/contextmanager.py", line 54, in _transaction
    session.commit_transaction()
  File "/Users/suhail/Workspace/neo4j/neo4j-django-tutorial/tutorialenv/lib/python3.6/site-packages/neo4j/v1/bolt.py", line 177, in commit_transaction
    self.sync()
  File "/Users/suhail/Workspace/neo4j/neo4j-django-tutorial/tutorialenv/lib/python3.6/site-packages/neo4j/v1/bolt.py", line 164, in sync
    self.connection.sync()
  File "/Users/suhail/Workspace/neo4j/neo4j-django-tutorial/tutorialenv/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 421, in sync
    count += self.fetch()
  File "/Users/suhail/Workspace/neo4j/neo4j-django-tutorial/tutorialenv/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 407, in fetch
    response.on_failure(metadata or {})
  File "/Users/suhail/Workspace/neo4j/neo4j-django-tutorial/tutorialenv/lib/python3.6/site-packages/neo4j/v1/bolt.py", line 222, in on_failure
    raise self.error_class(metadata)
neo4j.v1.api.CypherError: 0 (of class java.lang.Long)

**Comment by johanlundberg** [comment]
I have not seen that exception before. I will look in to it.

**Comment by i5uhail** [comment]
@johanlundberg Thanks a lot. 

Let me know if you need further info. 

I am running it on a mac with neo4j 3.2.1

**Comment by johanlundberg** [comment]
I have managed to recreate the error with Python 3.5, neo4j-python-driver 1.3.0 and neo4j 3.0.4 on Linux now. Sadly I don't really know what is happening. Hopefully I will have some more time too look in to it soon.

**Comment by johanlundberg** [comment]
Ok, found it.

Seems like the this is the issue, https://github.com/neo4j/neo4j/issues/9353.
The workaround/fix? is to set cypher.default_language_version=3.1 in neo4j.conf and restart the database.

I still get some "Exception ignored in: <bound method Driver.__del__ of <neo4j.v1.direct.DirectDriver" but those seem to have no effect on the queries.

**Comment by i5uhail** [comment]
@johanlundberg Unfortunately i am still facing the issue. :(

**Comment by johanlundberg** [comment]
Using the following versions:
Django==1.10.7
neo4j-driver==1.3.1

Python 3.5.3
neo4j 3.2.1

After uncommenting cypher.default_language_version in $NEO4JDIR/conf/neo4j.conf and changing it to 3.1 I have no issues.

How are you running the Neo4j database? Using docker?

**Comment by i5uhail** [comment]
I am running it out of my MAC. Installed it with the DMG file that i downloaded from the neo4j website.

**Comment by johanlundberg** [comment]
If you run a query in the webui and prepend it with EXPLAIN, ex. EXPLAIN MATCH n=() RETURN n LIMIT 1. Does it say "Cypher version: CYPHER 3.1 ..." at the bottom of the result window?

**Comment by i5uhail** [comment]
It says 3.2.

`Cypher version: CYPHER 3.2, planner: COST, runtime: INTERPRETED.`

**Comment by johanlundberg** [comment]
Then you need to change the configuration as I discuss above or wait for the fix in https://github.com/neo4j/neo4j/pull/9354 to make it in to a release.
